<?php
$lang = [
    // --- Navigation & Common ---
    'dashboard' => 'Dashboard',
    'transactions' => 'Transactions',
    'scan_receipt' => 'Scan Receipt',
    'categories' => 'Categories',
    'reports' => 'Reports',
    'profile' => 'Profile',
    'logout' => 'Logout',
    'back' => 'Back',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'edit' => 'Edit',
    'delete' => 'Delete',
    'actions' => 'Actions',
    'date' => 'Date',
    'amount' => 'Amount',
    'category' => 'Category',
    'description' => 'Description',
    'notes' => 'Notes',
    'type' => 'Type',
    'income' => 'Income',
    'expense' => 'Expense',
    'expenses' => 'Expenses',

    // --- Dashboard ---
    'good_morning' => 'Good Morning',
    'good_afternoon' => 'Good Afternoon',
    'good_evening' => 'Good Evening',
    'welcome_back' => 'Welcome Back',
    'recent_activity' => 'Recent Activity',
    'see_all' => 'See All',
    'no_recent_transactions' => 'No recent transactions',
    'monthly_budgets' => 'Monthly Budgets',
    'set_goal' => 'Set Goal',
    'no_budget_goals' => 'No budget goals set yet.',
    'get_started' => 'Get Started',
    'used' => 'Used',
    'quick_actions' => 'Quick Actions',
    'add_new' => 'Add New',
    'advisor' => 'Advisor',
    'budget' => 'Budget',
    'stats' => 'Stats',

    // --- Add Transaction ---
    'add_transaction' => 'Add Transaction',
    'new_transaction' => 'New Transaction',
    'save_transaction' => 'Save Transaction',
    'save_expense' => 'Save Expense',
    'save_income' => 'Save Income',
    'select_or_type' => 'Select or type...',
    'add_note_optional' => 'Add a note (optional)',

    // --- View Transactions (History) ---
    'all_transactions' => 'All Transactions',
    'all' => 'All',
    'no_records_found' => 'No records found.',
    'no_transactions_found' => 'No transactions found.',
    'confirm_delete' => 'Are you sure you want to delete this?',
    'delete_transaction' => 'Delete this transaction?',

    // --- Reports ---
    'premium_reports' => 'Premium Reports',
    'analyze_lifestyle' => 'Analyze your financial lifestyle.',
    'report_type' => 'Report Type',
    'monthly' => 'Monthly',
    'yearly' => 'Yearly',
    'month' => 'Month',
    'year' => 'Year',
    'total_spent' => 'Total Spent',
    'total_income' => 'Total Income',
    'monthly_comparison' => 'Monthly Comparison',
    'expense_breakdown' => 'Expense Breakdown',
    'category_details' => 'Category Details',
    'monthly_trends' => 'Monthly Trends',
    'daily_spending_flow' => 'Daily Spending Flow',
    'high_spending_alert' => 'High Spending Alert',
    'on_track' => 'On Track',
    'spending_balanced' => 'Your spending is balanced.',
    'ready_to_track' => 'Ready to Track',
    'no_expenses_found' => 'No expenses found',
    'start_adding_expenses' => 'Start adding expenses to populate the chart.',
    'try_changing_date' => 'Try changing the date filter.',

    // --- Profile ---
    'app_settings' => 'App Settings',
    'currency' => 'Currency',
    'security' => 'Security',
    'change_password' => 'Change Password',
    'new_password' => 'New Password',
    'confirm_password' => 'Confirm Password',
    'data_privacy' => 'Data & Privacy',
    'export_data' => 'Export Data',
    'reset_all_data' => 'Reset All Data',
    'reset_confirm' => 'Are you sure? This will delete ALL your transactions permanently.',
    'joined' => 'Joined',
    'saved' => 'Saved',
    'unsaved_changes' => 'Unsaved Changes',
    'tap_save' => 'Tap save to apply',
    'profile_updated' => 'Profile updated successfully!',
    'password_updated' => 'Password updated!',
    'password_mismatch' => 'Passwords do not match.',
    'password_too_short' => 'Password must be at least 6 characters.',
    'invalid_image' => 'Invalid image format.',
    'all_data_deleted' => 'All transactions deleted.',

    // --- Scan Receipt ---
    'ai_receipt_scanner' => 'AI Receipt Scanner',
    'scanner_subtitle' => 'Upload a receipt and let our AI extract the details.',
    'tap_to_upload' => 'Tap to Upload',
    'drag_and_drop' => 'or drag and drop',
    'change_image' => 'Change Image',
    'scan_now' => 'Scan Now',
    'initializing' => 'Initializing...',
    'analyzing_receipt' => 'Our AI robot is analyzing your receipt',
    'receipt_scanned' => 'Receipt Scanned!',
    'transaction_added' => 'Transaction has been added successfully.',
    'store_name' => 'Store Name',
    'scan_another' => 'Scan Another',

    // --- Set Budget ---
    'set_budget_title' => 'Set Budget Goal',
    'control_spending' => 'Control your monthly spending',
    'current_budgets' => 'Current Budgets',
    'monthly_limit' => 'Monthly Limit',
    'limit_desc' => 'Set a spending limit for this category',
    'back_dashboard' => 'Back to Dashboard',
    'set_budget' => 'Set Budget',
    'category_placeholder' => 'e.g. Food, Entertainment',

    // --- AI Advisor ---
    'financial_advisor' => 'Financial Advisor',
    'analyzing_finances' => 'Analyzing your finances...',
    'ai_powered_insight' => 'AI Powered Insight',
    'crunching_numbers' => 'Crunching the numbers...',
    'generate_new_insight' => 'Generate New Insight',
    'insight_secure' => 'Insights are generated securely using Gemini AI based on your recent transaction history.',
    'authentication_error' => 'Authentication Error',
    'network_error' => 'Network Error',
    'check_connection' => 'Please check your connection and try again.',
    'spending_alert_msg' => '<strong>%s</strong> is %s%% of expenses.',
    'scanning_progress_1' => 'Scanning...',
    'scanning_progress_2' => 'Identifying Text...',
    'scanning_progress_3' => 'Extracting Dates...',
    'scanning_progress_4' => 'Analyzing Amounts...',
    'scanning_progress_5' => 'Finalizing...',

    // --- Manage Categories ---
    'manage_categories' => 'Manage Categories',
    'customize_labels' => 'Customize your financial labels.',
    'create_new' => 'Create New',
    'category_name' => 'Category Name',
    'color_tag' => 'Color Tag',
    'pick_color' => 'Tap to pick a color',
    'save_category' => 'Save Category',
    'expense_categories' => 'Expense Categories',
    'income_categories' => 'Income Categories',
    'no_custom_expense' => 'No custom expense categories yet.',
    'no_custom_income' => 'No custom income categories yet.',
    'confirm_delete_category' => 'Delete this category?',
    'category_added' => 'Category added successfully!',
    'error_adding_category' => 'Error adding category.',
    'category_deleted' => 'Category deleted.',

    // --- Edit Transaction ---
    'edit_transaction_title' => 'Edit Transaction',
    'edit_desc' => 'Update your transaction details',
    'save_changes' => 'Save Changes',

    // --- Processing Messages ---
    'fill_all_fields' => 'All fields except description are required.',
    'transaction_failed' => 'Failed to add transaction.',
    'budget_updated_msg' => 'Budget updated for %s!',
    'budget_set_msg' => 'Budget set for %s!',
    'category_amount_required' => 'Category and Amount are required.',
    'db_error' => 'Database Error: ',

    // --- Mobile Footer ---
    'home' => 'Home',
    'history' => 'History',
    'scan' => 'Scan',
    'report' => 'Report',

    // --- Login / Signup ---
    'login_title' => 'Login - Budget Tracker Pro',
    'sign_in_desc' => 'Sign in to manage your finances',
    'email_address' => 'Email Address',
    'password' => 'Password',
    'sign_in' => 'Sign In',
    'no_account' => "Don't have an account?",
    'create_one' => 'Create one',
    'signup_title' => 'Sign Up - Budget Tracker Pro',
    'create_account' => 'Create Account',
    'start_tracking' => 'Start tracking your finances today',
    'username' => 'Username',
    'already_have_account' => 'Already have an account?',
];
