<?php
$lang = [
    // --- Navigation & Common ---
    'dashboard' => 'ダッシュボード',
    'transactions' => '取引履歴',
    'scan_receipt' => 'レシートスキャン',
    'categories' => 'カテゴリー',
    'reports' => 'レポート',
    'profile' => 'プロフィール',
    'logout' => 'ログアウト',
    'back' => '戻る',
    'save' => '保存',
    'cancel' => 'キャンセル',
    'edit' => '編集',
    'delete' => '削除',
    'actions' => '操作',
    'date' => '日付',
    'amount' => '金額',
    'category' => 'カテゴリー',
    'description' => '説明',
    'notes' => 'メモ',
    'type' => '種類',
    'income' => '収入',
    'expense' => '支出',
    'expenses' => '支出',

    // --- Dashboard ---
    'good_morning' => 'おはようございます',
    'good_afternoon' => 'こんにちは',
    'good_evening' => 'こんばんは',
    'welcome_back' => 'お帰りなさい',
    'recent_activity' => '最近の活動',
    'see_all' => 'すべて表示',
    'no_recent_transactions' => '最近の取引はありません',
    'monthly_budgets' => '月間予算',
    'set_goal' => '目標設定',
    'no_budget_goals' => '予算目標が設定されていません',
    'get_started' => '始める',
    'used' => '使用済み',
    'quick_actions' => 'クイックアクション',
    'add_new' => '新規追加',
    'advisor' => 'アドバイザー',
    'budget' => '予算',
    'stats' => '統計',

    // --- Add Transaction ---
    'add_transaction' => '取引を追加',
    'new_transaction' => '新規取引',
    'save_transaction' => '取引を保存',
    'save_expense' => '支出を保存',
    'save_income' => '収入を保存',
    'select_or_type' => '選択または入力...',
    'add_note_optional' => 'メモを追加（任意）',

    // --- View Transactions (History) ---
    'all_transactions' => 'すべての取引',
    'all' => 'すべて',
    'no_records_found' => 'レコードが見つかりません。',
    'no_transactions_found' => '取引が見つかりません。',
    'confirm_delete' => '本当に削除しますか？',
    'delete_transaction' => 'この取引を削除しますか？',

    // --- Reports ---
    'premium_reports' => 'プレミアムレポート',
    'analyze_lifestyle' => 'あなたの財務ライフスタイルを分析します。',
    'report_type' => 'レポートの種類',
    'monthly' => '月次',
    'yearly' => '年次',
    'month' => '月',
    'year' => '年',
    'total_spent' => '総支出',
    'total_income' => '総収入',
    'monthly_comparison' => '月次比較',
    'expense_breakdown' => '支出の内訳',
    'category_details' => 'カテゴリー詳細',
    'monthly_trends' => '月次トレンド',
    'daily_spending_flow' => '日次支出フロー',
    'high_spending_alert' => '支出超過アラート',
    'on_track' => '順調です',
    'spending_balanced' => '支出のバランスが取れています。',
    'ready_to_track' => '追跡の準備完了',
    'no_expenses_found' => '支出が見つかりません',
    'start_adding_expenses' => '経費を追加してチャートを表示しましょう。',
    'try_changing_date' => '日付フィルタを変更してみてください。',

    // --- Profile ---
    'app_settings' => 'アプリ設定',
    'currency' => '通貨',
    'security' => 'セキュリティ',
    'change_password' => 'パスワード変更',
    'new_password' => '新しいパスワード',
    'confirm_password' => 'パスワード確認',
    'data_privacy' => 'データとプライバシー',
    'export_data' => 'データのエクスポート',
    'reset_all_data' => 'すべてのデータをリセット',
    'reset_confirm' => 'よろしいですか？これにより、すべての取引データが永久に削除されます。',
    'joined' => '登録日',
    'saved' => '貯蓄額',
    'unsaved_changes' => '保存されていない変更',
    'tap_save' => 'タップして保存',
    'profile_updated' => 'プロフィールが更新されました！',
    'password_updated' => 'パスワードが更新されました！',
    'password_mismatch' => 'パスワードが一致しません。',
    'password_too_short' => 'パスワードは6文字以上である必要があります。',
    'invalid_image' => '無効な画像形式です。',
    'all_data_deleted' => 'すべての取引が削除されました。',

    // --- Scan Receipt ---
    'ai_receipt_scanner' => 'AIレシートスキャナー',
    'scanner_subtitle' => 'レシートをアップロードすると、AIが詳細を抽出します。',
    'tap_to_upload' => 'タップしてアップロード',
    'drag_and_drop' => 'またはドラッグ＆ドロップ',
    'change_image' => '画像を変更',
    'scan_now' => '今すぐスキャン',
    'initializing' => '初期化中...',
    'analyzing_receipt' => 'AIロボットがレシートを分析中',
    'receipt_scanned' => 'スキャン完了！',
    'transaction_added' => '取引が正常に追加されました。',
    'store_name' => '店舗名',
    'scan_another' => '別のレシートをスキャン',

    // --- Set Budget ---
    'set_budget_title' => '予算目標を設定',
    'control_spending' => '月々の支出を管理しましょう',
    'current_budgets' => '現在の予算',
    'monthly_limit' => '月間制限',
    'limit_desc' => 'このカテゴリーの支出制限を設定します',
    'back_dashboard' => 'ダッシュボードに戻る',
    'set_budget' => '予算を設定',
    'category_placeholder' => '例：食費、エンターテイメント',

    // --- AI Advisor ---
    'financial_advisor' => 'ファイナンシャルアドバイザー',
    'analyzing_finances' => '財務状況を分析中...',
    'ai_powered_insight' => 'AIによるインサイト',
    'crunching_numbers' => '計算中...',
    'generate_new_insight' => '新しいインサイトを生成',
    'insight_secure' => 'インサイトは、最近の取引履歴に基づいてGemini AIを使用して安全に生成されます。',
    'authentication_error' => '認証エラー',
    'network_error' => 'ネットワークエラー',
    'check_connection' => '接続を確認して、もう一度お試しください。',
    'spending_alert_msg' => '<strong>%s</strong> は支出の %s%% です。',
    'scanning_progress_1' => 'スキャン中...',
    'scanning_progress_2' => 'テキストを識別中...',
    'scanning_progress_3' => '日付を抽出中...',
    'scanning_progress_4' => '金額を分析中...',
    'scanning_progress_5' => '仕上げ中...',

    // --- Manage Categories ---
    'manage_categories' => 'カテゴリー管理',
    'customize_labels' => '財務ラベルをカスタマイズします。',
    'create_new' => '新規作成',
    'category_name' => 'カテゴリー名',
    'color_tag' => 'カラータグ',
    'pick_color' => 'タップして色を選択',
    'save_category' => 'カテゴリーを保存',
    'expense_categories' => '支出カテゴリー',
    'income_categories' => '収入カテゴリー',
    'no_custom_expense' => 'カスタム支出カテゴリーはまだありません。',
    'no_custom_income' => 'カスタム収入カテゴリーはまだありません。',
    'confirm_delete_category' => 'このカテゴリーを削除しますか？',
    'category_added' => 'カテゴリーが追加されました！',
    'error_adding_category' => 'カテゴリーの追加エラー。',
    'category_deleted' => 'カテゴリーが削除されました。',

    // --- Edit Transaction ---
    'edit_transaction_title' => '取引を編集',
    'edit_desc' => '取引の詳細を更新します',
    'save_changes' => '変更を保存',

    // --- Processing Messages ---
    'fill_all_fields' => '説明以外のすべてのフィールドは必須です。',
    'transaction_failed' => '取引の追加に失敗しました。',
    'budget_updated_msg' => '%s の予算を更新しました！',
    'budget_set_msg' => '%s の予算を設定しました！',
    'category_amount_required' => 'カテゴリーと金額は必須です。',
    'db_error' => 'データベースエラー： ',

    // --- Mobile Footer ---
    'home' => 'ホーム',
    'history' => '履歴',
    'scan' => 'スキャン',
    'report' => 'レポート',

    // --- Login / Signup ---
    'login_title' => 'ログイン - Budget Tracker Pro',
    'sign_in_desc' => '家計簿管理へようこそ',
    'email_address' => 'メールアドレス',
    'password' => 'パスワード',
    'sign_in' => 'ログイン',
    'no_account' => 'アカウントをお持ちでないですか？',
    'create_one' => '新規登録',
    'signup_title' => '新規登録 - Budget Tracker Pro',
    'create_account' => 'アカウント作成',
    'start_tracking' => '今日から家計管理を始めましょう',
    'username' => 'ユーザー名',
    'already_have_account' => 'すでにアカウントをお持ちですか？',
];
